<cfoutput>
	<div>
		<cb-media-gallery
			gallery-class='#args.galleryClass#'
			gallery-id='#args.gallerylId#'
			:file-list='#args.listing#'
			:image-info='#args.moreInfo#'
			media-folder='#args.folder#'
		></cb-media-gallery>
	</div>
</cfoutput>