name: cbCommerce API CI

# Only on Development we build snapshots
on:
  push:
    branches:
      - development
      - master

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      MYSQL_DATABASE: cbcommerce
      MYSQL_USER: cbcommerce
      MYSQL_PASSWORD: "c6C0mm3rc3!"
      MYSQL_ROOT_PASSWORD: "c6C0mm3rc3!"
    strategy:
      fail-fast: false
      matrix:
        cfengine: [ "lucee5", "adobe2018", "adobe2021" ]
        javaVersion: [ "openjdk11" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Database
        run: |
            docker run -d -p "3306:3306" --name mariadb -e 'MYSQL_DATABASE=${{env.MYSQL_DATABASE}}' -e 'MYSQL_USER=${{env.MYSQL_USER}}' -e 'MYSQL_PASSWORD=${{env.MYSQL_PASSWORD}}' -e 'MYSQL_ROOT_PASSWORD=${{env.MYSQL_ROOT_PASSWORD}}' mariadb

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Setup .env For Runner
        run: |
          touch .env
          printf "ENVIRONMENT=development\n" >> .env
          printf "DB_HOST=127.0.0.1\n" >> .env
          printf "DB_DATABASE=${{env.MYSQL_DATABASE}}\n" >> .env
          printf "DB_USER=${{ env.MYSQL_USER }}\n" >> .env
          printf "DB_PASSWORD=${{ env.MYSQL_PASSWORD }}\n" >> .env

      - name: Cache CommandBox Dependencies
        uses: actions/cache@v1
        if: ${{ true }}
        with:
          path: ~/.CommandBox/artifacts
          key: ${{ runner.OS }}-commandbox-cache-${{ hashFiles( 'box.json' ) }}-${{ hashFiles( 'modules/contentbox/box.json' ) }}
          restore-keys: |
            ${{ runner.OS }}-commandbox-cache-${{ hashFiles( 'box.json' ) }}-${{ hashFiles( 'modules/contentbox/box.json' ) }}

      - name: Install Dependencies
        run: |
          box run-script harness:install

      - name: Start ${{ matrix.cfengine }}/${{ matrix.javaVersion }} Server
        run: |
          # Startup the Server
          docker run -d -p "8080:8080" --name app  -v './test-harness:/app' -v ./:/app/modules/cbcommerce -v ./build:/app/modules/cbcommerce/test-harness ortussolutions/commandbox:${{matrix.cfengine}}

      - name: Run Migrations and Seed Database
        run: |
          curl http://127.0.0.1:8080?seed=true

      - name: Run Tests
        run: |
          mkdir tests/results/web
          box package set testbox.runner="http://127.0.0.1:8080/tests/runner.cfm"
          box testbox run --verbose outputFile=tests/results/web/test-results outputFormats=json,antjunit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: tests/results/**/*.xml
          check_name: "${{ matrix.cfengine }}/${{ matrix.javaVersion }} Test Results"

      - name: Upload Test Results Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: contentbox-test-results-${{ matrix.cfengine }}
          path: |
            tests/results/**/*

      - name: Failure Debugging Info
        if: ${{ failure() }}
        run: |
          docker logs app

  #############################################
  # Build cbCommerce
  #############################################
  build:
    name: Build & Publish
    needs: tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_API_TOKEN }}

      - name: Setup Environment Variables For Build Process
        id: current_version
        run: |
          echo "VERSION=`cat box.json | jq '.version' -r`" >> $GITHUB_ENV
          # master or snapshot
          echo "BRANCH=master" >> $GITHUB_ENV
          if [ $GITHUB_REF == 'refs/heads/development' ]
          then
            echo "BRANCH=development" >> $GITHUB_ENV
          fi

      - name: Build Docs
        run: |
          # Normalize swagger doc results
          cp -v tests/results/contentbox-test-results-lucee@5/contentbox-swagger.json tests/results/
          #ls -lR tests/results
          # Run Docs Build
          box run-script build:allDocs

      - name: Build cbCommerce Variants for ${{ env.BRANCH }} v${{ env.VERSION }}
        run: |
          ant -Dcontentbox.version=${{ env.VERSION }} -Dbuild.number=${{ github.run_number }} -Dbuild.branch=${{ env.BRANCH }} -f build/build.xml
          cat build/build-contentbox/module/box.json

      - name: List Variants
        run: ls -R
        working-directory: build/build-contentbox

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: contentbox-variants
          path: |
            artifacts/**/*

      - name: Upload Binaries to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "downloads.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "artifacts"
          DEST_DIR: "ortussolutions"

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "apidocs.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "build/build-contentbox/apidocs"
          DEST_DIR: "contentbox/${{ env.VERSION }}"

      - name: Publish
        run: |
          ROOT_DIR=`pwd`
          cd $ROOT_DIR/build/build-contentbox/module && box forgebox publish
          cd $ROOT_DIR/build/build-contentbox/site && box forgebox publish
          cd $ROOT_DIR/build/build-contentbox/installer && box forgebox publish
          cd $ROOT_DIR/build/build-contentbox/installer-module && box forgebox publish

      - name: Inform Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coding
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: 'cbCommerce Built with ${{ job.status }}!'
          SLACK_TITLE: "cbCommerce Build"
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
