name: Pull Requests

on:
  pull_request:
    branches:
      - development

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      MYSQL_DATABASE: cbcommerce
      MYSQL_USER: cbcommerce
      MYSQL_PASSWORD: "c6C0mm3rc3!"
      MYSQL_ROOT_PASSWORD: "c6C0mm3rc3!"
    strategy:
      fail-fast: false
      matrix:
        cfengine: [ "lucee5", "adobe2018", "adobe2021" ]
        javaVersion: [ "openjdk11" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Database
        run: |
            docker run -d -p "3306:3306" --name mariadb -e 'MYSQL_DATABASE=${{env.MYSQL_DATABASE}}' -e 'MYSQL_USER=${{env.MYSQL_USER}}' -e 'MYSQL_PASSWORD=${{env.MYSQL_PASSWORD}}' -e 'MYSQL_ROOT_PASSWORD=${{env.MYSQL_ROOT_PASSWORD}}' mariadb

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Setup .env For Runner
        run: |
          touch .env
          printf "ENVIRONMENT=development\n" >> .env
          printf "DB_HOST=127.0.0.1\n" >> .env
          printf "DB_DATABASE=${{env.MYSQL_DATABASE}}\n" >> .env
          printf "DB_USER=${{ env.MYSQL_USER }}\n" >> .env
          printf "DB_PASSWORD=${{ env.MYSQL_PASSWORD }}\n" >> .env

      - name: Cache CommandBox Dependencies
        uses: actions/cache@v1
        if: ${{ true }}
        with:
          path: ~/.CommandBox/artifacts
          key: ${{ runner.OS }}-commandbox-cache-${{ hashFiles( 'box.json' ) }}-${{ hashFiles( 'modules/contentbox/box.json' ) }}
          restore-keys: |
            ${{ runner.OS }}-commandbox-cache-${{ hashFiles( 'box.json' ) }}-${{ hashFiles( 'modules/contentbox/box.json' ) }}

      - name: Install Dependencies
        run: |
          box run-script harness:install

      - name: Start ${{ matrix.cfengine }}/${{ matrix.javaVersion }} Server
        run: |
          # Startup the Server
          docker run -d -p "8080:8080" --name app  -v './test-harness:/app' -v ./:/app/modules/cbcommerce -v ./build:/app/modules/cbcommerce/test-harness ortussolutions/commandbox:${{matrix.cfengine}}

      - name: Run Migrations and Seed Database
        run: |
          curl http://127.0.0.1:8080?seed=true

      - name: Run Tests
        run: |
          mkdir tests/results/web
          box package set testbox.runner="http://127.0.0.1:8080/tests/runner.cfm"
          box testbox run --verbose outputFile=tests/results/web/test-results outputFormats=json,antjunit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: tests/results/**/*.xml
          check_name: "${{ matrix.cfengine }}/${{ matrix.javaVersion }} Test Results"

      - name: Upload Test Results Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: contentbox-test-results-${{ matrix.cfengine }}
          path: |
            tests/results/**/*

      - name: Failure Debugging Info
        if: ${{ failure() }}
        run: |
          docker logs app

  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: Ortus-Solutions/commandbox-action@v1.0.2
        with:
          cmd: run-script format:check
